# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d38d9d5ed6b12956eb9a5bf5dc569d2a12ffddfce7fb0e60e3a3d80e42879abfe7b1f0519a1129d79df25aad83a838ee49f762dfb97f834bbbf9cdf472690fb3

test:
  secret_key_base: b0bf233beedc3267f29219f08c15020ae8c20c12c679f1d3faec6873d34f6b7628382b623e882d50cc2fa2a0c514f1175fffd5f6b4a79e901fb3915bab6c81c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
